name: Desplegar infraestructura y código

on:
    push:
        branches:
            - main


jobs:
    terraform-deploy:
        runs-on: ubuntu-lastest
        steps:
            - name: Descargar el codigo
              uses: actions/checkout@v3
            
            - name: Terraform apply
              run: terraform apply -auto-approve

